// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ZTE/Knitter/knitter-monitor/daos (interfaces: PodDaoInterface)

package mockdaos

import (
	daos "github.com/ZTE/Knitter/knitter-monitor/daos"
	gomock "github.com/golang/mock/gomock"
)

// Mock of PodDaoInterface interface
type MockPodDaoInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockPodDaoInterfaceRecorder
}

// Recorder for MockPodDaoInterface (not exported)
type _MockPodDaoInterfaceRecorder struct {
	mock *MockPodDaoInterface
}

func NewMockPodDaoInterface(ctrl *gomock.Controller) *MockPodDaoInterface {
	mock := &MockPodDaoInterface{ctrl: ctrl}
	mock.recorder = &_MockPodDaoInterfaceRecorder{mock}
	return mock
}

func (_m *MockPodDaoInterface) EXPECT() *_MockPodDaoInterfaceRecorder {
	return _m.recorder
}

func (_m *MockPodDaoInterface) Delete(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Delete", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodDaoInterfaceRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0, arg1)
}

func (_m *MockPodDaoInterface) Get(_param0 string, _param1 string) (*daos.PodForDB, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0, _param1)
	ret0, _ := ret[0].(*daos.PodForDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPodDaoInterfaceRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0, arg1)
}

func (_m *MockPodDaoInterface) Save(_param0 *daos.PodForDB) error {
	ret := _m.ctrl.Call(_m, "Save", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPodDaoInterfaceRecorder) Save(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0)
}
